sonar.projectKey=snaptale-frontend
sonar.projectName=snaptale-frontend
sonar.issue.ignore.multicriteria=userVideos,autocompleteComponent
sonar.issue.ignore.multicriteria.userVideos.ruleKey=Web:S4084
sonar.issue.ignore.multicriteria.userVideos.resourceKey=**/*.vue
sonar.issue.ignore.multicriteria.autocompleteComponent.ruleKey=Web:S6840
sonar.issue.ignore.multicriteria.autocompleteComponent.resourceKey=**/RegisterForm.vue
sonar.sources=app,server
