sonar.projectKey=snaptale-frontend
sonar.projectName=snaptale-frontend
sonar.issue.ignore.multicriteria=userVideos
sonar.issue.ignore.multicriteria.userVideos.ruleKey=Web:S4084
sonar.issue.ignore.multicriteria.userVideos.resourceKey=**/*.vue
sonar.sources=app,server
