spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.trustCertificateKeyStorePassword=${DB_TRUSTSTORE_PASSWORD}

snaptale.security.secure-cookies=true
snaptale.media.directory=${MEDIA_DIRECTORY}
snaptale.security.frontend-url=${FRONTEND_URL}
snaptale.keycloak.realm-url=${KEYCLOAK_REALM_URL}
snaptale.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}

logging.structured.format.console=ecs
