spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.trustCertificateKeyStorePassword=${DB_TRUSTSTORE_PASSWORD}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

application.security.secure-cookies=true
application.media.directory=${MEDIA_DIRECTORY}
application.security.frontend-url=${FRONTEND_URL}
application.keycloak.realm-url=${KEYCLOAK_REALM_URL}
application.keycloak.client-secret=${KEYCLOAK_CLIENT_SECRET}
application.mail.from=${MAIL_FROM}

logging.structured.format.console=ecs
