spring.datasource.url=jdbc:mysql://localhost:3306/snaptale
spring.datasource.username=root
spring.datasource.password=root

spring.mail.host=localhost
spring.mail.port=1025

snaptale.security.secure-cookies=false
snaptale.media.directory=media
snaptale.security.frontend-url=http://localhost:3000
snaptale.keycloak.realm-url=http://localhost:9000/realms/snaptale
snaptale.keycloak.client-secret=snaptale-local-secret
snaptale.mail.from=noreply@snaptale.local

logging.level.com.vertyll.snaptale=DEBUG
