spring.datasource.url=jdbc:mysql://localhost:3306/snaptale
spring.datasource.username=root
spring.datasource.password=root

spring.mail.host=localhost
spring.mail.port=1025

application.security.secure-cookies=false
application.media.directory=media
application.security.frontend-url=http://localhost:3000
application.keycloak.realm-url=http://localhost:9000/realms/snaptale
application.keycloak.client-secret=snaptale-local-secret
application.mail.from=noreply@application.local

logging.level.com.vertyll.snaptale=DEBUG
