spring.datasource.url=jdbc:mysql://localhost:3306/snaptale
spring.datasource.username=root
spring.datasource.password=root

snaptale.security.secure-cookies=false
snaptale.media.directory=media
snaptale.security.frontend-url=http://localhost:3000
snaptale.keycloak.realm-url=http://localhost:9000/realms/snaptale
snaptale.keycloak.client-secret=snaptale-local-secret

logging.level.com.vertyll.snaptale=DEBUG
