spring.application.name=snaptale-backend
spring.profiles.default=local
spring.threads.virtual.enabled=true
spring.main.banner-mode=off

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-missing-creator-properties=true

spring.servlet.multipart.max-file-size=${application.media.max-video-size}
spring.servlet.multipart.max-request-size=110MB

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.session.jdbc.initialize-schema=never

server.port=8080
server.shutdown=graceful
server.tomcat.use-relative-redirects=true
server.servlet.session.timeout=10h
server.servlet.session.cookie.name=SNAPTALE_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.cookie.secure=${application.security.secure-cookies}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

application.media.max-video-size=100MB
application.media.max-image-size=5MB
application.media.avatar-size=512

application.keycloak.client-id=snaptale-backend
application.keycloak.audience=snaptale-api

logging.level.org.flywaydb.core.internal.database.base.Database=ERROR
